### ISSUE TITLE
13 years to sync msg 

### ISSUE THREAD

**Issue by Waterloodown** [Gulden/gulden-dev#30]
When you first install the wallet it gives 13 years to sync msg before a peer becomes available. This might scare some users off :)

**Comment by cydg** [comment]
Needs additional condition to show a message like 'waiting for first blocks' when none is received yet.

**Comment by mjmacleod** [comment]
Yeah - though I think we change straight to just making this a percentage.
The date thing is stupid anyway, it confuses and scares new users and users who don't want to understand the internals of how the blockchain works (and people should not have to understand these things).
