### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by mjmacleod** [Gulden/gulden-dev#44]
Update UI in preparation for 1.5.1 release.

**Comment by BioMike** [comment]
Hi MaNI,

I managed to get the translation working (I was using the old guldencoin-qt binary, which wasn't removed).

The Dutch translation surfaces a bug in the GUI. The "backup"-button in the main UI uses the string from the File menu. In the Dutch translation the string is pretty long, which causes the text to "overflow" the button box. Fixing this would be to allow the button to have a separate string "Backup".

**Comment by mjmacleod** [comment]
Thanks, already aware of that one, new UI is still 'in progress' and intention is indeed to change that string to just "Backup", there will be several other new strings and/or string changes as well.

**Comment by BioMike** [comment]
Ok, I'll look out for them.
